### ISSUE TITLE
Supporting for Vue projects

### ISSUE THREAD

**Issue by junjie-xyz** [cdaringe/standard-damn-it#2]
Waiting for prettier-standard to support formatting .vue file. 
It would be great if your tool can initialize configuration for Vue projects then.

**Comment by cdaringe** [comment]
no doubt! if that prettier-standard supports it, you can now just use `npx standard-damn-it {src,lib,test}/**/*.{js,ts,vue}`, etc, and it'll just work.

I'm not a vue user, so I can't comment much beyond that, but the hook is in place. :)
